# Generated by Django 5.2.1 on 2025-05-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
