# Generated by Django 5.2.1 on 2025-05-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="username"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
